### ISSUE TITLE
添加block报错

### ISSUE THREAD

**Issue by ifrit2000** [umijs/umi-blocks#18]
$ umi block add ant-design-pro/analysis
✔ Parse url and args
✔ Git fetch
✔ Git checkout master
✔ Git pull
✖  error     AssertionError [ERR_ASSERTION]: /home/anthony/.umi/blocks/github.com/umijs/umi-blocks/ant-design-pro/analysis don't exists 
    at /home/anthony/IdeaProjects/hodgepodge-web/node_modules/umi-build-dev/lib/plugins/commands/block/index.js:231:27
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/anthony/IdeaProjects/hodgepodge-web/node_modules/umi-build-dev/lib/plugins/commands/block/index.js:36:103)
    at _next (/home/anthony/IdeaProjects/hodgepodge-web/node_modules/umi-build-dev/lib/plugins/commands/block/index.js:38:194)
    at process._tickCallback (internal/process/next_tick.js:68:7)

package.json
```
{
  "name": "ant-design-pro",
  "version": "2.1.1",
  "description": "An out-of-box UI solution for enterprise applications",
  "private": true,
  "scripts": {
    "start": "cross-env APP_TYPE=site umi dev",
    "start:no-mock": "cross-env MOCK=none umi dev",
    "dev": "cross-env APP_TYPE=site umi dev",
    "dev:no-mock": "cross-env MOCK=none umi dev",
    "build": "umi build",
    "analyze": "cross-env ANALYZE=1 umi build",
    "lint:style": "stylelint \"src/**/*.less\" --syntax less",
    "lint": "eslint --ext .js src mock tests && npm run lint:style",
    "lint:fix": "eslint --fix --ext .js src mock tests && npm run lint:style",
    "lint-staged": "lint-staged",
    "lint-staged:js": "eslint --ext .js",
    "test": "umi test",
    "test:component": "umi test ./src/components",
    "test:all": "node ./tests/run-tests.js",
    "prettier": "node ./scripts/prettier.js"
  },
  "dependencies": {
    "ant-design-pro": "^2.1.1",
    "antd": "^3.10.9",
    "classnames": "^2.2.6",
    "dva": "^2.4.0",
    "hash.js": "^1.1.5",
    "lodash": "^4.17.10",
    "lodash-decorators": "^6.0.0",
    "memoize-one": "^4.0.0",
    "moment": "^2.22.2",
    "nzh": "^1.0.3",
    "path-to-regexp": "^2.4.0",
    "prop-types": "^15.5.10",
    "query-string": "^6.0.0",
    "rc-animate": "^2.4.4",
    "react": "^16.6.3",
    "react-container-query": "^0.11.0",
    "react-document-title": "^2.0.3",
    "react-media": "^1.8.0",
    "umi-request": "^1.0.0"
  },
  "devDependencies": {
    "babel-eslint": "^10.0.1",
    "cross-env": "^5.1.1",
    "cross-port-killer": "^1.0.1",
    "eslint": "^5.4.0",
    "eslint-config-airbnb": "^17.0.0",
    "eslint-config-prettier": "^3.0.1",
    "eslint-plugin-babel": "^5.3.0",
    "eslint-plugin-compat": "^2.6.2",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsx-a11y": "^6.1.2",
    "eslint-plugin-markdown": "^1.0.0-beta.6",
    "eslint-plugin-react": "^7.11.1",
    "husky": "^1.2.0",
    "lint-staged": "^8.1.0",
    "prettier": "1.15.2",
    "stylelint": "^9.8.0",
    "stylelint-config-prettier": "^4.0.0",
    "stylelint-config-standard": "^18.0.0",
    "umi": "^2.3.0-0",
    "umi-plugin-pro-block": "^1.2.0",
    "umi-plugin-react": "^1.3.0-0"
  },
  "lint-staged": {
    "**/*.{js,ts,tsx,json,jsx,less}": [
      "node ./scripts/lint-prettier.js",
      "git add"
    ],
    "**/*.{js,jsx}": "npm run lint-staged:js",
    "**/*.less": "stylelint --syntax less"
  },
  "engines": {
    "node": ">=8.0.0"
  },
  "husky": {
    "hooks": {
      "pre-commit": "npm run lint-staged"
    }
  }
}

```

**Comment by tsinglemon** [comment]
需要保证项目目录为空才可以创建区块。
所以你可以先用命令创建好，再把.git或者其他文件放进去就好了

**Comment by sorrycc** [comment]
是 `ant-design-pro/Analysis`，不是 `ant-design-pro/analysis`。
