### ISSUE TITLE
error: pathspec 'master' did not match any file(s) known to git

### ISSUE THREAD

**Issue by zhaocz2015** [umijs/umi-blocks#23]
```
$ umi block add ant-design-pro/Analysis
√ Parse url and args
√ Git fetch
× Git checkout master
×  error     Error: Error: Command failed: git checkout master
error: pathspec 'master' did not match any file(s) known to git


    at D:\tmp\learnAntd\xboot-antd\node_modules\umi-build-dev\lib\plugins\commands\block\index.js:154:15
    at Generator.throw (<anonymous>)
    at asyncGeneratorStep (D:\tmp\learnAntd\xboot-antd\node_modules\umi-build-dev\lib\plugins\commands\block\index.js:36:103)
    at _throw (D:\tmp\learnAntd\xboot-antd\node_modules\umi-build-dev\lib\plugins\commands\block\index.js:38:291)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Hello Guys , what is the reason for the error

**Comment by syLi95** [comment]
我也遇到了同样的问题？想问你解决了吗？

**Comment by huangziye** [comment]
> 我也遇到了同样的问题？想问你解决了吗？

umi版本的问题，你看的你的umi版本是不是2.8.6，另外，你还需要把全局的umi卸载掉及执行 npm uninstall  -g umi

**Comment by syLi95** [comment]
> > 我也遇到了同样的问题？想问你解决了吗？
> 
> umi版本的问题，你看的你的umi版本是不是2.8.6，另外，你还需要把全局的umi卸载掉及执行npm uninstall -g umi

是2.8.6,，感觉好像不是版本问题，在另一台的电脑是2.8.6就可以
