### ISSUE TITLE
添加block失败: TypeError: opts.remoteLog is not a function 

### ISSUE THREAD

**Issue by zlx362211854** [umijs/umi-blocks#46]
具体操作为：
```
zlxdeMacBook-Pro:umitest zlx$ npx umi block add AccountSettings --js
✔ 😁  Parse url and args
✖  error     TypeError: opts.remoteLog is not a function 
    at /workspace/umitest/node_modules/umi-build-dev/lib/plugins/commands/block/index.js:234:14
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/workspace/umitest/node_modules/umi-build-dev/lib/plugins/commands/block/index.js:128:103)
    at _next (/workspace/umitest/node_modules/umi-build-dev/lib/plugins/commands/block/index.js:130:194)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

环境信息为：
```
zlxdeMacBook-Pro:umitest zlx$ npx -v
9.7.1
zlxdeMacBook-Pro:umitest zlx$ node -v
v8.10.0
zlxdeMacBook-Pro:umitest zlx$ npm ls umi
ant-design-pro@1.0.0 /workspace/umitest
└── umi@2.9.0 


```

**Comment by sorrycc** [comment]
在 umi@2.9.1 里修复了。

**Comment by zlx362211854** [comment]
> 在 umi@2.9.1 里修复了。

谢谢🙏
